- day: Monday
  end_time: '22:00'
  start_time: '11:00'
- day: Tuesday
  end_time: '22:00'
  start_time: '11:00'
- day: Wednesday
  end_time: '22:00'
  start_time: '11:00'
- day: Thursday
  end_time: '22:00'
  start_time: '11:00'
- day: Friday
  end_time: '22:00'
  start_time: '11:00'
- day: Saturday
  end_time: '22:00'
  start_time: '11:00'
- day: Sunday
  end_time: '22:00'
  start_time: '11:00'
