business_hours:
- day: Monday
  end_time: '24:00'
  start_time: '18:00'
- day: Tuesday
  end_time: '24:00'
  start_time: '18:00'
- day: Wednesday
  end_time: '24:00'
  start_time: '18:00'
- day: Thursday
  end_time: '24:00'
  start_time: '18:00'
- day: Friday
  end_time: '24:00'
  start_time: '18:00'
- day: Saturday
  end_time: '24:00'
  start_time: '12:00'
- day: Sunday
  end_time: '24:00'
  start_time: '12:00'
