site_name: Hi
theme:
  name: material
nav:
  - 'Home': 'index.md'
  - 'Database': 'DATABASE.md'
  - 'Commands':
    - 'Ticket System': 'commands/tickets.md'
    - 'Keyword System': 'commands/keywords.md'
    - 'Role Requesting': 'commands/roles.md'
    - 'Miscellaneous': 'commands/miscellaneous.md'
