site_name: DragonBot documentation
theme:
  name: material
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 


        name: Switch to dark mode

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - 'Home': 'index.md'
  - 'Database': 'DATABASE.md'
  - 'Commands':
    - 'Ticket System': 'commands/tickets.md'
    - 'Keyword System': 'commands/keywords.md'
    - 'Role Requesting': 'commands/roles.md'
    - 'Miscellaneous': 'commands/miscellaneous.md'
